language: node_js
sudo: false
node_js:
- '10'
os:
- linux

script:
- npm test
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
  - "/^v.*$/"
deploy:
  provider: npm
  edge: true
  email: lgreco@mozilla.com
  cleanup: false
  on:
    tags: true
    repo: rpl/flow-coverage-report
    branch: master
  api_token:
    secure: aVewjQT9RfNL+49Wj1gwdA+x6GHGhNQvzCPHCTEn/kVdxQgl+uy6klLOEfSNiVeADXjzD4U9/q7RMfxPXCt7aMYbPxE6MFmbiOSWQ0g7jPi4x4pgkhxEjyeIH1z/+mYcob4IKFVse0F016woo+14LpKD75vljeNrgSqeyy+VJOH8aw+3dKWOFHKqq29HbKxe/CImtnU6SCpLO4/3kx27qzI1qYVTHBSV6+qwgGOX9OxoC5wyjFNMHlaci0v1gNinTDZPUOgsKk5GTVttCwbQGT17SWAoHacMFrDBPkXSiET68GLbzsdO2ncx243dw/pAaoOHU/fUoqO6nYyJGXbnXwWuvQSk312ImNGct0elQfAy0EQTpPnyvOom/ctNRlOv24b32djJPcefeWG9HB0tGvWRKWUzOXoRIy5vPV8QOnoIQ8hJb0DcxQQKPlT869hINUiq1pNqhEVp5X7aMiLF1ozxeJMWXld6ezQPtOtTTBx5t/YlSsoVgqg1y+Ls+ESJIPJXxT8Lh3IVwX8wPaRJJ/oIax3QZONdFH7m9HjXByi1h0zS3cbkbjggFe2KmM5TEFEg1gQdL3I5pVoiFknoy7fTzw6GC8S1DKnKBJFViuAycTFZxa5/OX151cOs6qfOMJyJ6fLnNorl8o3s8cgBOM+wv5Dmjz1fc9KZnhGD7ns=
